name: Rust Continuous Integration
env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PG_VER: 17

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  rust-format:
    name: Rust Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo Format
        run: cargo fmt --all -- --check
